### ISSUE TITLE
Looking for new contributors to contribute

### ISSUE THREAD

**Issue by endormi** [endormi/dj#12]
This repository is beginner friendly, keep in mind that you do not need Django to work with this. 

Specifically meant for people who are looking into using Django, since this gives great amount of information about Django and it's capabilities.

**Comment by ispite** [comment]
I would like to participate, but what a project you are doing.

**Comment by endormi** [comment]
@ispite thanks for commenting. It's a basic readme.md about Django (Python's web framework). You could check #7 and follow the windows download as for formatting.

**Comment by ispite** [comment]
Why do you give me a link to the issue, I use Windows and do not see problems in installing the framework?

**Comment by endormi** [comment]
I meant it as adding an django installation tutorial (with mac and linux) to readme.md. You don't actually need to install Django to work with this repo, this is just a readme file. @ispite

**Comment by endormi** [comment]
@ispite are you still up for contributing? I added a django bootstrap boilerplate that needs help, for usage check the boilerplate [README.md ](https://github.com/endormi/django/blob/master/boilerplate/README.md)
